PAGE_MAPPING = {
    '/_b_a_c_k_e_n_d_/Diagnostics/registration/':'SD-P-REG',
    '/_b_a_c_k_e_n_d_/Diagnostics/login/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/patient/create/':'SD-P-REG',
    '/_b_a_c_k_e_n_d_/Diagnostics/latest-patient-id/':'SD-P-REG',
    '/_b_a_c_k_e_n_d_/Diagnostics/patient/update/<str:patient_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/patients_get_barcode/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/save-barcodes/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/latest-bill-no/':'SD-P-REG',
    '/_b_a_c_k_e_n_d_/Diagnostics/get-existing-barcode/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/patient-get/':'SD-P-REG',
    '/_b_a_c_k_e_n_d_/Diagnostics/patients/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/patients/<str:patient_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/get_received_samples/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/Diagnostics/patient_report/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/test_details/':'SD-P-BILL',
    '/_b_a_c_k_e_n_d_/Diagnostics/test_details_test/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/test_parameters/<str:test_name>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/compare_test_details/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/get_patient_test_details/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/test-value/save/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/test-value/update/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/update_dispatch_status/<str:patient_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/sample-collector/':'SD-P-REG',
    '/_b_a_c_k_e_n_d_/Diagnostics/refby/':'SD-P-REG',
    '/_b_a_c_k_e_n_d_/Diagnostics/clinical_name/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/clinical_name/last/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/test-report/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/test-values/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/test-values/<str:patient_id>/<int:test_index>/approve/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/test-values/<str:patient_id>/<int:test_index>/rerun/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/update-test-detail/<str:patient_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/get_sample_collected/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/update_sample_collected/<str:patient_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/sample_patient/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/sample_status/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/testvalue/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/update_sample_status/<str:patient_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/samplestatus-testvalue/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/patient_overview/':'SD-P-OD',
    '/_b_a_c_k_e_n_d_/Diagnostics/patient_test_status/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/all-patients/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/overall_report/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/patient_test_sorting/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/credit_amount/<str:patient_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/update-credit/<str:patient_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/send-email/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/SalesVisitLog/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/SalesVisitLogReport/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/hospitallabform/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/save-logistic-data/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/get_logistic_data/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/patient/get/<str:patient_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/getlogisticdata/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/check-barcode/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/savesamplecollector/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/updatesamplecollectordetails/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/patient/get/<str:patient_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/consolidated-data/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/generate-invoice/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/get-invoices/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/update-invoice/<str:invoice_number>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/delete-invoice/<str:invoice_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/salesdashboard/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/getsalesmapping/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/logisticdashboard/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/search_refund/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/verify_and_process_refund/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/search_cancellation/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/upload-pdf/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/get-file/<str:file_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/send-whatsapp/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/get_patients/':'SD-P-BILL',
    '/_b_a_c_k_e_n_d_/Diagnostics/patient/update_billing/<str:patient_id>/':'SD-P-BILL',
    '/_b_a_c_k_e_n_d_/Diagnostics/patient/tests/<str:patient_id>/<str:date>/':'SD-P-BILL',
    '/_b_a_c_k_e_n_d_/Diagnostics/clinical_name/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/clinical_name/last/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/clinical-names/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/clinical-names/<str:referrerCode>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/clinical-names/<str:referrerCode>/first_approve/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/clinical-names/<str:referrerCode>/final_approve/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/search_refund/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/verify_and_process_refund/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/generate_otp_refund/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/generate_otp_cancellation/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/search_cancellation/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/verify_and_process_cancellation/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/refund_cancellation_logs/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/mou-preview/<str:file_id>/':'',
    '/_b_a_c_k_e_n_d_/Diagnostics/dashboard-data/':'',    
}

PAGE_ACTION_MAPPING = {
    'GL-P-EPM': {
        'DELETE':'RWD',
    },
}

GEN_ACTION_MAPPING = {
    'POST': 'RW',
    'PUT': 'RW',
    'DELETE': 'RW',
    'GET': 'R',
}
